apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # The port you want to expose
  type: LoadBalancer  # Use 'LoadBalancer' if you are in a cloud environment
